## miniconf makefiles ## 1.1 ##

TOPDIR := ../..

deskno2_src = deskno2.c
deskno2_cflags = -DPLUGIN $(GTK3_CFLAGS) 
deskno2_libs = $(GTK3_LIBS) 
deskno2_type = lib 

include $(TOPDIR)/.config/rules.mk
