## miniconf makefiles ## 1.1 ##

TOPDIR := ../..

separator_src = separator.c
separator_cflags = -DPLUGIN $(GTK3_CFLAGS) 
separator_libs = $(GTK3_LIBS) 
separator_type = lib 

include $(TOPDIR)/.config/rules.mk
